[tool.poetry]
name = "quickstart_cpp"
version = "0.1.0"
description = "C++ FL client Quickstart example with Flower"
authors = ["The Flower Authors <enquiries@flower.dev>"]


[tool.poetry.dependencies]
python = "^3.7"
#flwr = "^0.18.0"
flwr = { path = "../../", develop = true }  # Development
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
